kind: Service
apiVersion: v1
metadata:
  name: api-gateway
spec:
  type: NodePort
  selector:
    app: spring-cloud-zuul
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 32001
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-zuul
  labels:
    app: spring-cloud-zuul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-zuul
  template:
    metadata:
      labels:
        app: spring-cloud-zuul
        version: latest
    spec:
      hostname: zuul
      subdomain: zuul
      containers:
      - name: spring-cloud-zuul
        image: 192.168.0.8:5000/api-gateway:latest
        ports:
        - name: http
          containerPort: 9000